
  %load_ext autoreload : magic command de Jupyter de autoreload
  
  %autoreload 2 : recarga todo automáticamente(2)

In [99]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [100]:
# PAQUETE LIBRERIAS ANALISIS DE DATOS y de SKLEARN
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

import sys
sys.path.append('..')

from src.eda import reporte_calidad
from src.eda import clasificar_formato_fecha

### FACT_MANTENIMIENTO

In [101]:
directory =  r'C:\Users\jbard\Desktop\Library\@CURSOS ACTUALES\@Data Analitycs\Python projects\Mineria-simulacion v2'
fact_mtto_PC= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PC_raw.csv')
fact_mtto_PN= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PN_raw.csv')
fact_mtto_PS= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PS_raw.csv')

#### 1) FACT_MANTENIMIENTO_PC

1era verificacion de calidad

In [102]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PC,nombre_df='fact_mtto_PC')

--- Resumen: fact_mtto_PC ---
Total filas: 2735
Filas duplicadas: 27 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009872,2684,51,1.86,7
1,orden_id,str,0.009872,2735,0,0.00,2708
2,parada_id,str,0.009872,2735,0,0.00,2708
3,fecha_apertura,str,0.009872,2735,0,0.00,1271
4,equipo_id,str,0.009872,2735,0,0.00,10
5,tipo_orden,str,0.009872,2735,0,0.00,2
6,horas_hombre,float64,0.009872,2735,0,0.00,306
7,num_tecnicos,int64,0.009872,2735,0,0.00,3
8,costo_repuestos_soles,float64,0.009872,2735,0,0.00,2233

In [107]:
fact_mtto_PC[fact_mtto_PC['repuesto_principal'].isnull()] # Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

fact_mtto_PC['repuesto_principal']=fact_mtto_PC['repuesto_principal'].fillna('indeterminado')
fact_mtto_PC

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
0,OT-004314,PAR-005657,PC-EQ-06,2024-05-28,Correctiva,12.7,3,Faja/correa,493.0
1,OT-005483,PAR-007230,PC-EQ-10,2027-08-24,Correctiva,13.1,2,Ninguno (solo mano de obra),4001.0
2,OT-003042,PAR-004020,PC-EQ-01,2027-09-11,Preventiva,9.7,3,Ninguno (solo mano de obra),1002.0
3,OT-005094,PAR-006708,PC-EQ-09,2025-10-03,Correctiva,0.6,2,Ninguno (solo mano de obra),5051.0
4,OT-004318,PAR-005661,PC-EQ-06,2024-06-06,Correctiva,1.0,2,indeterminado,5757.0
...,...,...,...,...,...,...,...,...,...
2730,OT-003349,PAR-004424,PC-EQ-03,2024-03-20,Correctiva,0.9,2,Sello mecánico,7199.0
2731,OT-002985,PAR-003939,PC-EQ-01,2026-11-24,Correctiva,3.7,2,Sensor/instrumento,2870.0
2732,OT-004610,PAR-006038,PC-EQ-07,2025-03-24,Correctiva,8.7,2,Sello mecánico,385.0
2733,OT-003238,PAR-004289,PC-EQ-02,2026-09-06,Correctiva,2.2,2,Motor eléctrico,5208.0
2734,OT-004256,PAR-005590,PC-EQ-05,2027-09-23,Correctiva,7.9,1,Faja/correa,676.0

VERIFICACION TIPOS DE FECHA QUE HAY EN LA COLUMNA 'FECHA_APERTURA'

In [104]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PC['fecha_apertura'],
        'tipo_fecha': fact_mtto_PC['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-05-28        YMD
1     2027-08-24        YMD
2     2027-09-11        YMD

tipo_fecha
YMD    2735
Name: count, dtype: int64

In [108]:
validar_fechas(fact_mtto_PC,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-05-28   YMD_TIME
1        2027-08-24   YMD_TIME
2        2027-09-11   YMD_TIME
3        2025-10-03   YMD_TIME
4        2024-06-06   YMD_TIME
...             ...        ...
2730     2024-03-20   YMD_TIME
2731     2026-11-24   YMD_TIME
2732     2025-03-24   YMD_TIME
2733     2026-09-06   YMD_TIME
2734     2027-09-23   YMD_TIME

[2735 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

#### 2) FACT_MANTENIMIENTO_PS

In [106]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PS,nombre_df='fact_mtto_PS')

--- Resumen: fact_mtto_PS ---
Total filas: 2422
Filas duplicadas: 23 (0.95%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009496,2376,46,1.9,7
1,orden_id,str,0.009496,2422,0,0.0,2399
2,parada_id,str,0.009496,2422,0,0.0,2399
3,fecha_apertura,str,0.009496,2422,0,0.0,1204
4,equipo_id,str,0.009496,2422,0,0.0,10
5,tipo_orden,str,0.009496,2422,0,0.0,2
6,horas_hombre,float64,0.009496,2422,0,0.0,277
7,num_tecnicos,int64,0.009496,2422,0,0.0,3
8,costo_repuestos_soles,float64,0.009496,2422,0,0.0,1999

In [118]:
fact_mtto_PS['repuesto_principal']=fact_mtto_PS['repuesto_principal'].fillna('indeterminado')
fact_mtto_PS

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
0,OT-006852,PAR-009048,PS-EQ-06,2024-10-14,Preventiva,3.8,3,Sensor/instrumento,1951.0
1,OT-006899,PAR-009107,PS-EQ-06,2025-06-24,Correctiva,1.8,1,Rodamiento,5263.0
2,OT-007564,PAR-010013,PS-EQ-09,2024-09-17,Correctiva,10.5,2,Sello mecánico,4010.0
3,OT-006307,PAR-008321,PS-EQ-04,2024-12-29,Correctiva,1.0,2,Sensor/instrumento,2647.0
4,OT-005711,PAR-007532,PS-EQ-01,2027-01-31,Preventiva,4.4,3,Rodamiento,2069.0
...,...,...,...,...,...,...,...,...,...
2417,OT-007068,PAR-009326,PS-EQ-06,2027-11-15,Correctiva,14.7,3,Ninguno (solo mano de obra),1804.0
2418,OT-005951,PAR-007840,PS-EQ-02,2026-08-01,Correctiva,4.3,3,Ninguno (solo mano de obra),872.0
2419,OT-005653,PAR-007450,PS-EQ-01,2026-03-28,Preventiva,5.5,2,Faja/correa,744.0
2420,OT-007014,PAR-009255,PS-EQ-06,2027-01-30,Preventiva,9.1,2,Ninguno (solo mano de obra),2173.0
2421,OT-005734,PAR-007565,PS-EQ-01,2027-06-27,Correctiva,1.0,2,Revestimiento (liner),7778.0

In [119]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PS['fecha_apertura'],
        'tipo_fecha': fact_mtto_PS['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-10-14   YMD_TIME
1     2025-06-24   YMD_TIME
2     2024-09-17   YMD_TIME

tipo_fecha
YMD_TIME    2422
Name: count, dtype: int64

In [122]:
validar_fechas(fact_mtto_PS,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-10-14   YMD_TIME
1        2025-06-24   YMD_TIME
2        2024-09-17   YMD_TIME
3        2024-12-29   YMD_TIME
4        2027-01-31   YMD_TIME
...             ...        ...
2417     2027-11-15   YMD_TIME
2418     2026-08-01   YMD_TIME
2419     2026-03-28   YMD_TIME
2420     2027-01-30   YMD_TIME
2421     2027-06-27   YMD_TIME

[2422 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

#### 3) FACT_MANTENIMIENTO_PN

In [124]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PN,nombre_df='fact_mtto_PN')

--- Resumen: fact_mtto_PN ---
Total filas: 2829
Filas duplicadas: 28 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,orden_id,str,0.009897,2829,0,0.0,2801
1,parada_id,str,0.009897,2829,0,0.0,2801
2,equipo_id,str,0.009897,2829,0,0.0,10
3,fecha_apertura,datetime64[us],0.009897,2829,0,0.0,1273
4,tipo_orden,str,0.009897,2829,0,0.0,2
5,horas_hombre,float64,0.009897,2829,0,0.0,299
6,num_tecnicos,int64,0.009897,2829,0,0.0,3
7,repuesto_principal,str,0.009897,2829,0,0.0,8
8,costo_repuestos_soles,float64,0.009897,2829,0,0.0,2310

In [127]:
fact_mtto_PS[fact_mtto_PS['repuesto_principal'].isnull()] # Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

fact_mtto_PS['repuesto_principal']=fact_mtto_PS['repuesto_principal'].fillna('indeterminado')
fact_mtto_PS

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
0,OT-006852,PAR-009048,PS-EQ-06,2024-10-14,Preventiva,3.8,3,Sensor/instrumento,1951.0
1,OT-006899,PAR-009107,PS-EQ-06,2025-06-24,Correctiva,1.8,1,Rodamiento,5263.0
2,OT-007564,PAR-010013,PS-EQ-09,2024-09-17,Correctiva,10.5,2,Sello mecánico,4010.0
3,OT-006307,PAR-008321,PS-EQ-04,2024-12-29,Correctiva,1.0,2,Sensor/instrumento,2647.0
4,OT-005711,PAR-007532,PS-EQ-01,2027-01-31,Preventiva,4.4,3,Rodamiento,2069.0
...,...,...,...,...,...,...,...,...,...
2417,OT-007068,PAR-009326,PS-EQ-06,2027-11-15,Correctiva,14.7,3,Ninguno (solo mano de obra),1804.0
2418,OT-005951,PAR-007840,PS-EQ-02,2026-08-01,Correctiva,4.3,3,Ninguno (solo mano de obra),872.0
2419,OT-005653,PAR-007450,PS-EQ-01,2026-03-28,Preventiva,5.5,2,Faja/correa,744.0
2420,OT-007014,PAR-009255,PS-EQ-06,2027-01-30,Preventiva,9.1,2,Ninguno (solo mano de obra),2173.0
2421,OT-005734,PAR-007565,PS-EQ-01,2027-06-27,Correctiva,1.0,2,Revestimiento (liner),7778.0

In [128]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PN['fecha_apertura'],
        'tipo_fecha': fact_mtto_PN['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-09-23   YMD_TIME
1     2026-03-06   YMD_TIME
2     2027-09-29   YMD_TIME

tipo_fecha
YMD_TIME    2829
Name: count, dtype: int64

In [129]:
validar_fechas(fact_mtto_PN,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-09-23   YMD_TIME
1        2026-03-06   YMD_TIME
2        2027-09-29   YMD_TIME
3        2026-02-25   YMD_TIME
4        2024-05-03   YMD_TIME
...             ...        ...
2824     2024-08-22   YMD_TIME
2825     2026-04-04   YMD_TIME
2826     2026-05-07   YMD_TIME
2827     2026-05-12   YMD_TIME
2828     2027-11-02   YMD_TIME

[2829 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.